create table if not exists public.wap_prospects (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  nome text,
  segmento text,
  origem text,
  dados_publicos jsonb default '{}'::jsonb,
  atencoes jsonb default '[]'::jsonb,
  positivos jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.wap_journey_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  prospect_id text,
  event_type text not null,
  state text,
  segmento text,
  familia text,
  origem text,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.wap_leads (
  id bigint generated by default as identity primary key,
  session_id text,
  prospect_id text,
  nome text,
  contato text,
  mensagem text,
  segmento text,
  familia text,
  origem text,
  created_at timestamptz default now()
);

alter table public.wap_prospects enable row level security;
alter table public.wap_journey_events enable row level security;
alter table public.wap_leads enable row level security;

drop policy if exists "public_insert_journey" on public.wap_journey_events;
create policy "public_insert_journey" on public.wap_journey_events
for insert to anon with check (true);

drop policy if exists "public_insert_leads" on public.wap_leads;
create policy "public_insert_leads" on public.wap_leads
for insert to anon with check (true);
