const C=window.COURSE,total=C.reduce((n,m)=>n+m[1].length,0);let done=new Set(JSON.parse(localStorage.getItem('wapSemioticaDone')||'[]'));let currentKey='';
const views=[...document.querySelectorAll('.view')];function show(id){views.forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('aside button').forEach(b=>b.classList.toggle('active',b.dataset.view===id))}
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>show(b.dataset.view));
function render(){let mh='',cl='';C.forEach((m,mi)=>{mh+=`<article class="module" onclick="show('course')"><b>${String(mi+1).padStart(2,'0')}</b><h3>${m[0].replace(/^Módulo \d+ — /,'')}</h3><p>${m[1].length} aulas</p></article>`;cl+=`<h3>${m[0]}</h3>`;m[1].forEach((a,ai)=>{let k=mi+'-'+ai;cl+=`<article class="lessonRow ${done.has(k)?'done':''}" onclick="openLesson(${mi},${ai})"><span class="ico">${a[2]}</span><div><strong>${a[0]}</strong><p>${a[1]}</p></div><small>AULA ${String(ai+1).padStart(2,'0')}</small></article>`})});modulesHome.innerHTML=mh;courseList.innerHTML=cl;update()}
function openLesson(mi,ai){let a=C[mi][1][ai];currentKey=mi+'-'+ai;lessonModule.textContent=C[mi][0].toUpperCase();lessonTitle.textContent=a[0];lessonIntro.textContent=a[1];lessonVisual.textContent=a[2];lessonText.innerHTML=`<p>${content(a[0])}</p>`;lessonChallenge.textContent=challenge(a[0]);completeBtn.textContent=done.has(currentKey)?'AULA CONCLUÍDA ✓':'CONCLUIR AULA ✓';show('lesson')}
function content(t){let x={"O que é Semiótica?":"Semiótica é o estudo dos signos e de como produzimos significado. Cor, som, gesto, fotografia, palavra e movimento podem funcionar como signos.","Tipos de Signos":"Ícones se parecem com aquilo que representam. Índices apontam uma relação ou evidência. Símbolos dependem de convenções aprendidas.","Semiótica no delivery":"Vapor sugere calor. Condensação e gelo sugerem frio. Brilho, textura e enquadramento podem aumentar a percepção de frescor e desejo.","Semiótica em interfaces":"Um bom ícone antecipa uma ação. O texto continua disponível para confirmar significado, acessibilidade e evitar ambiguidade.","Movimento com significado":"Movimento deve explicar mudança de estado: algo entrou no carrinho, uma tarefa terminou, uma etapa foi liberada. Movimento sem função vira ruído."};return x[t]||`Nesta aula, observe como “${t}” influencia a interpretação. O significado nasce da relação entre o elemento percebido, o contexto e o repertório de quem observa.`}
function challenge(t){return `Encontre hoje um exemplo de “${t}” em um site, aplicativo, embalagem ou ambiente e explique em uma frase o significado transmitido.`}
completeBtn.onclick=()=>{done.add(currentKey);localStorage.setItem('wapSemioticaDone',JSON.stringify([...done]));completeBtn.textContent='AULA CONCLUÍDA ✓';render()}
function update(){let p=Math.round(done.size/total*100);progress.style.width=p+'%';pct.textContent=p+'%';bigPct.textContent=p+'%';doneCount.textContent=done.size+' / '+total+' aulas'}
function resetProgress(){done.clear();localStorage.removeItem('wapSemioticaDone');render()}
document.querySelectorAll('.quiz button').forEach(b=>b.onclick=()=>{quizFeedback.textContent=b.dataset.ok==='1'?'✓ Correto. O alerta é reconhecido antes da leitura.':'Observe qual símbolo você reconheceria como aviso instantaneamente.';quizFeedback.style.color=b.dataset.ok==='1'?'#63ff9a':'#ffd477'});render();